-- Migration 0026: pgvector semantic embeddings
--
-- Phase 3 — Cohere-embed-v3-multilingual (Idea 5)
-- Adds pgvector support and a 1024-dim embedding column to the services table.
-- Embeddings are generated by the `cohere-embed-v3-multilingual` deployment on
-- ORAN-FOUNDRY-resource (Azure AI Services, westus2).
--
-- After applying this migration:
--   1. Deploy FOUNDRY_EMBED_DEPLOYMENT env var (cohere-embed-v3-multilingual)
--   2. Enable the vector_search feature flag
--   3. Run the admin /api/admin/embeddings/reindex endpoint to populate embeddings
--   4. Newly published services receive embeddings automatically at publish time

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_available_extensions
    WHERE name = 'vector'
  ) THEN
    CREATE EXTENSION IF NOT EXISTS vector;

    EXECUTE '
      ALTER TABLE services
        ADD COLUMN IF NOT EXISTS embedding vector(1024)
    ';

    EXECUTE '
      CREATE INDEX IF NOT EXISTS idx_services_embedding_hnsw
        ON services USING hnsw (embedding vector_cosine_ops)
        WITH (m = 16, ef_construction = 64)
        WHERE embedding IS NOT NULL
    ';

    EXECUTE '
      CREATE INDEX IF NOT EXISTS idx_services_needs_embedding
        ON services (id)
        WHERE embedding IS NULL AND status = ''active''
    ';
  ELSE
    RAISE NOTICE 'pgvector extension is unavailable; skipping embedding column and indexes';
  END IF;
END $$;
